[package]
name = "protoc-plugin-bin"
version = "0.1.2"
edition = "2024"
description = "An internal crate for protoc-plugin-by-closure crate."
license = "Apache-2.0"
repository = "https://github.com/wada314/protoc-plugin-by-closure"

[dependencies]
anyhow = "1.0.95"
ipc-channel = "0.20.1"
protobuf-core = "0.1.0"

[[bin]]
name = "protoc-plugin-bin"
path = "src/main.rs"
